version: "3.5"
services:
  aicap-tech:
    container_name: aicap-tech
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    working_dir: /home/app
    command: sh -c "npm install && npm run dev"
